#os: osx
#language: go

# user docker services
#services:
#  - docker

# install comply
install:
  - go get github.com/strongdm/comply
#  - docker pull strongdm/comply
#  - docker run --rm -v "$PWD":/source -p 4000:4000 -it strongdm/comply

# copy the static files from s3 here
#before_script:
#  - copy the static files from s3 here

# check if bash is required or not
# if TRAVIS_EVENT is a cron, run the scheduler so that tickets are created.
# else then the event is a push/pull request event from github, so just perform a comply build
script:
  - comply scheduler
  - comply build
#  - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; 
#    then comply scheduler; 
#    else comply build;
#    fi

# if TRAVIS_EVENT is a cron, copy the state files to s3 bucket
# else copy the output directory files to s3 bucket
#before_deploy:
#  - copy static files to s3

# prevent Travis from resetting the working dir and deleting all changes made during the build with the skip_cleanup flag
#deploy:
#  - provider: s3
#    access_key_id: "YOUR AWS ACCESS KEY"
#    secret_access_key: "YOUR AWS SECRET KEY"
#    bucket: "S3 Bucket"
#    skip_cleanup: true
#  - provider: s3
#    access_key_id: "YOUR AWS ACCESS KEY"
#    secret_access_key: "YOUR AWS SECRET KEY"
#    bucket: "Second S3 Bucket"
#    skip_cleanup: true
