[build]
  command = "./build-netlify.sh"
  publish = "output"

[template.environment]
  GITHUB_TOKEN = 

[[headers]]
  for = "/*"
  [headers.values]
    # If you wish to password-protect the site, uncomment the following line:
    # Basic-Auth = "user:password"
    # You can put security response headers here
